### ISSUE TITLE
App Crashing At  "bottomNav.setMenuItemList(list);"

### ISSUE THREAD

**Issue by VaibhavJadiya** [wwdablu/LottieBottomNav#10]
I copied the entire code solved some basic errors and when I tried to build the Apk the app is crashing at "bottomNav.setMenuItemList(list);" and No further information mentioned in Android Studio.

Kindly tell me the solution for it

**Comment by wwdablu** [comment]
Working on the reported issue.

**Comment by wwdablu** [comment]
@VaibhavJadiya I ran the latest code and I did not observe any issue. The code has updated to use the latest version of the Lottie Library along with other updates like Gradle. Request you to please run the sample code and confirm if it works. If not, please share the stack trace. From what you have specified, it looks like there is an issue with the list object or the bottomNav object. Please share log for more information.

**Comment by CrezyProgrammer** [comment]
Adding this line in app level build.gradle slove the issue
android {
    ....
    dataBinding {
        enabled = true
    }
}

**Comment by wwdablu** [comment]
@VaibhavJadiya Please let me know if the issue has been resolved. If so, requesting you to please provide the resolution for other developers after which we can close the ticket.
