### ISSUE TITLE
implementation error

### ISSUE THREAD

**Issue by Lucifer-Otis** [wwdablu/LottieBottomNav#13]
1. Implemented the dependency in Gradle.
2. Error:
         - Failed to resolve: com.github.wwdablu:lottiebottomnav:1.2.0
         - Show in Project Structure dialog
         - Affected Modules: app

**Comment by VikashAnandJha** [comment]
i am also facing same problem

**Comment by wwdablu** [comment]
@Lucifer-Otis @VikashAnandJha 
Please use the following changes if using grade KTS:

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven(url="https://jitpack.io")
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven(url="https://jitpack.io")
    }
}
