### ISSUE TITLE
DataBinderMapperImpl & JSON parser issue

### ISSUE THREAD

**Issue by Cdik** [wwdablu/LottieBottomNav#4]
Hey!

DataBinding issue when using the library with AndroidX in Kotlin.
`Failed resolution of: Landroidx/databinding/DataBinderMapperImpl;`

When `dataBinding { enabled = true }` then it rises `Unable to parse composition`

Also reporter on [lottie-android](https://github.com/airbnb/lottie-android/issues/667#issuecomment-505459992) (might be related to JSON reader)

**Comment by Cdik** [comment]
Okay I just found a way to make it work. 

You have to put the lottie animation inside the `assets` folder (it crashes if inside the `raw` folder)
Declare the source to be `MenuItem.Source.Assets` and don't forget the `dataBinding { enabled = true }` in the gradle file otherwise you'll end up with `Landroidx/databinding/DataBinderMapperImpl;` error

**Comment by erKaranjeet** [comment]
after adding databinding i am getting the different issue. 
`Missing values for keyframe.`
