### ISSUE TITLE
Change text size and font.

### ISSUE THREAD

**Issue by HammadKhanAmigo** [wwdablu/LottieBottomNav#5]
**Is your feature request related to a problem? Please describe.**
App always need to implement new fonts and font sizes accordingly. And it is too bad when there is great work of someone like this library is but have no way to edit font.

**Describe the solution you'd like**
I would love to have following options when creating MenuItem:
   - .setFont()
   - .setSelectedTextSize(20f)
   - .setUnselectedTextSize(15f)

**Comment by wwdablu** [comment]
Started working on the issue. Will update the ticket accordingly.

**Comment by wwdablu** [comment]
Implementation provided in branch https://github.com/wwdablu/LottieBottomNav/tree/enhancement_1. @HammadKhanAmigo The changes have been made and is being tested for sanity. Once confirmed, will be merged to master and a release will be tagged.

**Comment by wwdablu** [comment]
Released.
https://github.com/wwdablu/LottieBottomNav/releases/tag/1.1.0
