### ISSUE TITLE
Sir how we add fragment in this.

### ISSUE THREAD

**Issue by Govindkishor** [wwdablu/LottieBottomNav#8]
sir please help me to put fragment in this .i want to know how i will add fragment in this on each click of menuitem .

**Comment by wwdablu** [comment]
Hello @Govindkishor 

The sample using Fragment is provided here.

https://github.com/wwdablu/LottieBottomNav/tree/minor_update_1.1.1/sample/src/main/java/com/wwdablu/soumya/lottiebottomnavsample

Do let me know if you have if need any more help.
